### ISSUE TITLE
inject manifest.json to html template?

### ISSUE THREAD

**Issue by mantou132** [oliviertassinari/serviceworker-webpack-plugin#10]
thank you very much

**Comment by oliviertassinari** [comment]
I don't understand.
What's the link between the ServiceWorker and the manifest?
Put it differently, what would be the win of doing so?

**Comment by mantou132** [comment]
sry.
I did not think clearly.
Just because manifest.json also needs to be directly accessible like sw.js

**Comment by oliviertassinari** [comment]
Sorry, I don't understand your use case.

**Comment by oliviertassinari** [comment]
I'm gonna close this issue for now. As far as I know the best solution to add a manifest is by declaring it directly in the `index.html`:
```html
 <link rel="manifest" href="/manifest.json" />
``` 
No need for a webpack plugin to do it. [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin) might interest you.
