### ISSUE TITLE
Install with Quasar-Framework

### ISSUE THREAD

**Issue by glittle** [oliviertassinari/serviceworker-webpack-plugin#15]
I'm trying to use this with the Quasar-Framework (https://github.com/quasarframework/quasar) but don't seem to have access to the webpack config file.

Any suggestion on how to integrate this into that environment?

The closest config seems to be the `.babelrc` file which is:

    {
      "presets": [["es2015", {"modules": false}], "stage-2"],
      "plugins": ["transform-runtime"],
      "comments": false
    }

As you can tell, I'm out of my element when it comes to webpack...

**Comment by oliviertassinari** [comment]
If you don't have access to the wepback configuration file, the best thing to do would be to use a different tool. For instance, https://github.com/GoogleChrome/sw-precache could be something that will interest you.
