### ISSUE TITLE
not working with require

### ISSUE THREAD

**Issue by dawidvdh** [oliviertassinari/serviceworker-webpack-plugin#2]
Hi i am trying to use your plugin but i'm not using es6 in my webpack set up and when i attempt to use it via require i get the following message:

```TypeError: ServiceWorkerWepbackPlugin is not a constructor```

Any Help would be Greatly Appreciated

**Comment by dawidvdh** [comment]
i seem to have figured it out, one needs to add `default` so it looks like:

```javascript
new ServiceWorkerWepbackPlugin.default({
      entry: path.join(__dirname, 'src/sw.js'),
      excludes: [
        '**/.*',
        '**/*.map',
        '*.html'
      ]
    })
```

**Comment by oliviertassinari** [comment]
Yes indeed. Can we close the issue?
