### ISSUE TITLE
Registering service worker from absolute path

### ISSUE THREAD

**Issue by mattiasewers** [oliviertassinari/serviceworker-webpack-plugin#21]
When the url is anything other than `/` the service worker fails as it's trying to fetch it from  e.g. `/foo/sw.js`.

**Comment by alibosworth** [comment]
I believe you need to set an option of `publicPath: "/"` - it seems really crazy that this isn't the default option, but I had the same issue and it seems to have fixed it.

**Comment by oliviertassinari** [comment]
@alibosworth I'm not sure what's the best default value is. But I tend to agree with you. It was I'm doing with this [PWA](https://github.com/oliviertassinari/SplitMe/blob/master/webpack.config.js#L225).

**Comment by mattiasewers** [comment]
@alibosworth Thanks, that fixed it. I agree that this should be the default.

**Comment by oliviertassinari** [comment]
Closed with 133ae6c06275bf418007417b88995e44c29b5a9d. Thanks guys for the feedback.
