### ISSUE TITLE
Fails and hangs if filename contains a '[hash]'

### ISSUE THREAD

**Issue by CircuitCoder** [oliviertassinari/serviceworker-webpack-plugin#24]
Currently, the plugin only looks for assets with the exact same name mentioned in the config file. But if a hash is included in the filename, the plugin won't be able to find it.

This results in a unhandled promise rejection, and the compilation hangs. It seems that the callback is never called if that problem happens. That may be related to #19.

**Comment by VeeteshJain** [comment]
+1
