### ISSUE TITLE
service worker not updated

### ISSUE THREAD

**Issue by alexey2baranov** [oliviertassinari/serviceworker-webpack-plugin#27]
Hello!

i wrote service worker and load it using your plugin success. But when i change my code in sw.js it doesn't updated in browser until i open devtool and force update it by devtools/Application/update or update on reload

i tried reload page 10+ times. Anyway get the first version of service worker as active and none others as installing or waiting

Thanks

**Comment by oliviertassinari** [comment]
The `sw.js` is cached for at most 24h, make sure you have disabled the browser cache.
