### ISSUE TITLE
Inlining the Service Worker

### ISSUE THREAD

**Issue by kmaraz** [oliviertassinari/serviceworker-webpack-plugin#28]
Is there any possibility to inline service worker provided?

**Comment by oliviertassinari** [comment]
What do you mean by inline? You could be interested having a look at the `template` option.

**Comment by kmaraz** [comment]
Webpack generates separate file with the service worker, but I would like to have service worker included in the app bundle, to ship it together with the app bundle. Is it possible through the `template` option?

**Comment by oliviertassinari** [comment]
>  I would like to have service worker included in the app bundle

That's the use case of including it in the app bundle? Sounds like you don't need that plugin for that use case.

**Comment by oliviertassinari** [comment]
I'm closing the issue. Sorry but I don't understand the value you would get from that feature.
