### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Khachatour** [oliviertassinari/serviceworker-webpack-plugin#29]
When I am using this plugin, I keep getting 

`(node:29634) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined
`
Can someone suggest an answer ?

**Comment by Khachatour** [comment]
I already fixed it, it cause by wrong webpack configuration, thanks!

**Comment by oliviertassinari** [comment]
@Khachatour So it's not on our side?

**Comment by Khachatour** [comment]
@oliviertassinari  100% no, But can you specify in error handling that it is from webpack. It took me a day to resolve that :) . For example to say that it comes from webpack configs ?

**Comment by oliviertassinari** [comment]
Do you have a reproduction example so I can have a look at?

**Comment by anthonator** [comment]
I'm running into this as well. @Khachatour could you post the solution?

**Comment by Khachatour** [comment]
@oliviertassinari Now I can't reproduce it, I am sure it came form my side. But I will try to reproduce that as soon as possible.  
@anthonator As I mentioned I can't reproduce it, but as I remember it was coming form wrong configuration for service worker, are you creating sw file by your own ? I will try to reproduce that as soon as possible and return here with exact solution ok?

**Comment by oliviertassinari** [comment]
No rush, let us know if you find something :).

**Comment by Khachatour** [comment]
@oliviertassinari I've reproduced the error, It comes when in your webpack dev configs you declare the usage of service worker plugin and then in plugins section declare the usage of plugin with this code below:
`new ServiceWorkerWebpackPlugin({
      entry: path.join(__dirname, 'src/sw.js'),
    })`
The error `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined` shows up. I think its when your declared path `src/sw.js` is not in the webpack output assets in development environment, or simply not correct path as I think. What you think ? 
@anthonator Here it is!! :)

**Comment by anthonator** [comment]
The issue I was having was definitely an issue with my entry file not being found. I had a typo. I think this is just an issue of better error handing/reporting.

**Comment by Khachatour** [comment]
@anthonator  I definitely agree with you. The error shown is not giving a clue what was wrong :)
