### ISSUE TITLE
Avoid compiler and linter exceptions in source file

### ISSUE THREAD

**Issue by Nckcol** [oliviertassinari/serviceworker-webpack-plugin#32]
My purpose is change trmplate from `var serviceWorkerOption = ...` to `self.serviceWorkerOption = ...` or even better `self._serviceWorkerOption = ...`.
It helps to avoid compiler and linter exceptions (such as 'variable is not defined') for source file

**Comment by oliviertassinari** [comment]
Yeah, getting a variable is not defined is the whole point. So you know you are not dealing with a native API but something injected, injected by the plugging. Having a linting warning is a good thing from my point of view.

**Comment by Nckcol** [comment]
Oh, my apologies
I've just realized i can access variable from `self` even if it's defined with `var`.
