### ISSUE TITLE
Support Webpack 3

### ISSUE THREAD

**Issue by kesne** [oliviertassinari/serviceworker-webpack-plugin#33]
Webpack 3 was just released, and it shouldn't have any breaking changes for this plugin. You should be able to just add it as another version in `peerDependencies`.

I'll submit a PR to add it into the `package.json` later today.

**Comment by oliviertassinari** [comment]
Thanks for opening that issue, we should definitely support Webpack 3.

> I'll submit a PR to add it into the package.json later today.

Awesome!
