### ISSUE TITLE
Multiple workers

### ISSUE THREAD

**Issue by GabrielGil** [oliviertassinari/serviceworker-webpack-plugin#41]
Hi!

First at all, thank you for this great plugin you made available for all of us.

I would like to register a second service worker (for firebase messaging) but I can't find an ideal solution that works well with webpack. I need to import some of the assets from webpack on this secondary service worker, but this seems an impossible mission.

If I instantiate twice the plugin on webpack, there's no way to register them both independently from the app (`runtime.register()`). 

Thank you in advance.

**Comment by oliviertassinari** [comment]
`serviceworker-webpack-plugin/lib/runtime` is a simple syntax sugar so you don't have to duplicate the service worker name. But in the case of using multiple service workers, that doesn't longer provide any value as you need to distinguish what's going to be registered. Don't use it, use tha native API.

**Comment by oliviertassinari** [comment]
I'm not sure that this change is going to be enough. I have never thought the API to work with multiple workers. Let me know what's needed to support that feature :).

**Comment by GabrielGil** [comment]
Hmm, not sure how the native loading would work, as I require other elements to be imported (i.e. images).

Will give it a thought on Monday and keep you posted. Thanks for answering.

**Comment by woutervanvliet** [comment]
Unless the scope is different, I don't think you can have more than 1 serviceworker. See: https://stackoverflow.com/questions/36000127/can-i-have-multiple-service-workers-both-intercept-the-same-fetch-request

But if you really need more than 1 - you can just use `navigator.serviceWorker.register('/sw.js', { scope: '/' })`.

**Comment by GabrielGil** [comment]
The idea was not to intercept the same request, but for other responsibilities, and in some of them, accessing webpack assets becomes handy.

**Comment by woutervanvliet** [comment]
I see.

If you have a good use-case, perhaps we can take a second look. But in general, I would recommend considering to use one ServiceWorker and let that one decide what code handles which requests. Separate handlers can be imported with either `importScripts`, or just `import` them like you normally would.

How would you see `serviceworker-webpack-plugin/lib/runtime` being used with several SW's?

**Comment by GabrielGil** [comment]
In order to not bloat this, with rather useless comments, let me analyze better my proposal. Maybe just if I get the registration of the service worker of the one using the `lib/runtime` would be enough.

Thank you for your answers. :)
