### ISSUE TITLE
Add support for dev-server ?

### ISSUE THREAD

**Issue by gwuhaolin** [oliviertassinari/serviceworker-webpack-plugin#42]
When used in dev-server, `/sw.js` is 404

**Comment by oliviertassinari** [comment]
It should be working. Might be linked to a wrong configuration of the plugin. Does that work in production?

**Comment by thehig** [comment]
I'm having the same issue, [Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.]. I'm currently investigating my webpack config

**Comment by oliviertassinari** [comment]
@thehig Thanks for letting us know! I'm going to improve the docs a bit.
