### ISSUE TITLE
registration.showNotification is not a function

### ISSUE THREAD

**Issue by stonecold123** [oliviertassinari/serviceworker-webpack-plugin#45]
I saw that the Html5 `new Notification` isn't supported on Android Chrome for web app notification ([topic](https://stackoverflow.com/questions/31512504/html5-notification-not-working-in-mobile-chrome)).  The alternative is to use `registration.showNotification('text.')`, but the registration provided from `runtime.register()` doesn't have the `showNotification` function. Is this function actually available?

Based on your example:
````
class Main extends Component {
  componentDidMount() {
    if (
      'serviceWorker' in navigator &&
      (window.location.protocol === 'https:' || window.location.hostname === 'localhost')
    ) {
      const registration = runtime.register()
      registerEvents(registration, {
        onInstalled: () => {
             registration.showNotification('Hello.')
        }
      })
    }
  }
}
````

**Comment by oliviertassinari** [comment]
Any solution to share? :)

**Comment by stonecold123** [comment]
@oliviertassinari 
I didn't realize that ` runtime.register()` returns just the `Promise` instead of the registration itself. I need to use `await  runtime.register()`.

**Comment by oliviertassinari** [comment]
Thanks for sharing!
