### ISSUE TITLE
ability to specify a different publicPath for sw.js from assets

### ISSUE THREAD

**Issue by rileylnapier** [oliviertassinari/serviceworker-webpack-plugin#46]
hi, im uploading my assets to a CDN... but my sw.js needs to be at the root of my domain.

i would like to specify assetPublicPath and swPublicPath

is this something we can add to the options?

**Comment by rileylnapier** [comment]
also, what benefit do i get from using 

```
if ('serviceWorker' in navigator && process.env.NODE_ENV === 'production') {
  runtime.register();
}
```

vs

```
if ('serviceWorker' in navigator && process.env.NODE_ENV === 'production') {
  navigator.serviceWorker.register('/sw.js');
}
```


??

**Comment by oliviertassinari** [comment]
You have the `publicPath` option. The benefit is about abstracting the service worker fetch location. It's optional.
