### ISSUE TITLE
Unable to get resource hash

### ISSUE THREAD

**Issue by andre487** [oliviertassinari/serviceworker-webpack-plugin#47]
It's very useful to have resource hash in service worker.  HTML Webpack Plugin can [inject resource with hash](https://github.com/jantimon/html-webpack-plugin#configuration) for validating resource cache, and it's useful if you have this information in Service Worker.

**Comment by woutervanvliet** [comment]
I'm a bit unsure as to what you exactly mean. By default, a list of assets emitted by webpack is included in your service worker. They all include the hash in their filename, if that's what you setup in your webpack config.

If you need more information about the build to be available in your ServiceWorker you can supply `transformOptions`, which receives all the webpack build info. In one of my own projects, I have it setup like so:

```js
const swPlugin = new ServiceWorkerWebpackPlugin({
    entry: path.join(context, 'src/sw.js'),
    publicPath: '/public/',
    filename: 'sw.js',
    transformOptions: (swOption) => {
        // The list of cachable assets contains contains, for each file,
        // a hash of their content. A complete hash of that would be
        // perfect as cache name.
        // We need to add a cache of the service worker file though,
        // as that one doesn't have a content cache
        const hash = crypto.createHash('sha1');
        hash.update([
            JSON.stringify(swOption.assets),
            fs.readFileSync(path.join(context, 'src/sw.js'), 'utf8'),
            isProduction ? '1' : Math.random(),
        ].join('-'));
        return {
            isProduction,
            watch,
            assets: swOption.assets,
            buildId: `${pkg.version}-${hash.digest('hex')}`,
        };
    },
});
```

And use `buildId` as cache name (`caches.open(serviceWorkerOption.buildId)`).

Hope this helps.

**Comment by AlexDubok** [comment]
I think it would be nice to have webpack build hash among the jsonStats object. It could be added to the cache name to make cache unique for every build. All that should be done is the change of[ this line](https://github.com/oliviertassinari/serviceworker-webpack-plugin/blob/master/src/index.js#L143) to true.
Or maybe it will more extendable if we could pass whole stats object as a plugin option?
