### ISSUE TITLE
sub directory filename

### ISSUE THREAD

**Issue by DrBoria** [oliviertassinari/serviceworker-webpack-plugin#53]
I'd like to add some filename like '/build/scope_a/sw.js'
But my application goes to donwload '/build' without other part of filename. Is there any case to implement filename with slash?
Thanks.

**Comment by woutervanvliet** [comment]
Fix on the way, in https://github.com/oliviertassinari/serviceworker-webpack-plugin/pull/36

**Comment by woutervanvliet** [comment]
@DrBoria could you confirm that the fix presented in #36 indeed solves your use case? If not, please provide more info on what you're trying to do.
