### ISSUE TITLE
Fails in webpack 4 with UglifyJsPlugin

### ISSUE THREAD

**Issue by enjikaka** [oliviertassinari/serviceworker-webpack-plugin#54]
> Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
> node_modules/serviceworker-webpack-plugin/lib/index.js:198:61

**Comment by woutervanvliet** [comment]
Work in progress, feel free to - temporarily - use `oliviertassinari/serviceworker-webpack-plugin#next` in your package.json. A webpack 4 compatible release will be released to npm asap.

**Comment by woutervanvliet** [comment]
@kontrollanten Looking into that. I just recently joined this project, so bear with us.

**Comment by kontrollanten** [comment]
I see! Thanks! Keep up the good work!

**Comment by woutervanvliet** [comment]
I just pushed out the first alpha with webpack 4 support. You can install this as `serviceworker-webpack-plugin@next'.

If you find any more issues, please do open an issue marked for the 1.0.0 milestone
