### ISSUE TITLE
Message handling

### ISSUE THREAD

**Issue by DrBoria** [oliviertassinari/serviceworker-webpack-plugin#61]
Can't send message to service worker from window and can't handle message in window from service worker. Is there any options to handle it?

I use handler in service worker:
`
self.addEventListener('message', (event) => {
  debugger;
});
`

And post message using:
`navigator.serviceWorker.controller.postMessage("ololo");`

And nothing.

**Comment by woutervanvliet** [comment]
Works fine for me.

Remember that you can only start sending messages to your ServiceWorker after it's been installed, which would typically be on the first pageload *after* your `serviceWorker.register` call.  Unless you respond to the install event with `skipWaiting`.

Hope this helps
