### ISSUE TITLE
How to start demo app in doc/

### ISSUE THREAD

**Issue by yiakwy** [oliviertassinari/serviceworker-webpack-plugin#62]
Hi there is no package.json file nor execution scripts in the root of docs. Could you explain me that how to use it to start the application

**Comment by devCrossNet** [comment]
hey,
clone the repo and install the dependencies, after everything is installed run the script `npm run docs:development`. That worked for me.

**Comment by yiakwy** [comment]
@devCrossNet Thanks. I installed the dependancies globally from the root of the project. That works for me now.

I will study it carefully. Basically I have understand how it works. Now I want to integrate Service Worker as computation and query loop. Could you give me some advice:

Since it is background thread, it has computation power,

(1) The programme has rendering loop render geometries. Instead of executing sequence by sequence, I want the programme do it in advance and wait for main page js programme to query

(2) Every geometry has unique Id generated by front end app, If I query for it, the user UI generated by React will becomes slow. Instead of executing sequence by seqence, I want the main page send a query to background thread (service worker), do some searching algorithms, and notify client page main thread when it is ready.

(3) If possible I want to implement a publisher and subscriber. But it seems that only one thread for one domain is allowed. How should organize my programmes?

here is the hierarchy of my codes 

```bash
backend
frontend
   src/
        module1
        UICom/
        common/
        module2
        module3/
        ....
        workers/
               router.js
               storage.js
               utils/
                     messager.js
                        
```

Thank you very much!

**Comment by devCrossNet** [comment]
Hey, are you talking about web-worker instead of service-worker? The purpose of a service worker is to serve as a gateway to the internet e.g. cache assets and get it from the cache instead of the network if your device is offline.

have a look at this doc: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by yiakwy** [comment]
Oh I get it. I am talking about a worker (maybe web worker, I will check it). 

I am trying to use service worker (a proxy thread) because  I just got ideas half a year ago from google when it introduced PWA / AMP caching into developers and companies. 

Is it possible?
