### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by choonkending** [oliviertassinari/serviceworker-webpack-plugin#7]
Not really an issue - just wanted to thank you for this plugin! 🎆 (Didn't know where else to thank you). 

It's lightweight!

I agree with your points. 

The issue with other plugins (which are really powerful) is that it is a bit too abstract for me, also couples us to webpack.

However, I've tried rolling my own implementation and hit the same problems you've listed in your README. 

Good work! I will hopefully be using this plugin in the projects I'm involved in once I experiment around with this more! 🎉

**Comment by choonkending** [comment]
(Closing as not really an issue)

**Comment by oliviertassinari** [comment]
@choonkending Thanks for those kind words.
