### ISSUE TITLE
Don't detect minification using webpack.optimize

### ISSUE THREAD

**Issue by shlomiassaf** [oliviertassinari/serviceworker-webpack-plugin#73]
In https://github.com/oliviertassinari/serviceworker-webpack-plugin/blob/master/src/index.js#L171-L173

With the new webpack, using this expression: 
```
 return plugin instanceof webpack.optimize.UglifyJsPlugin
```
Will throw:
```
RemovedPluginError: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
```

This should be change based on the version of webpack.

```
let minify;
if (Number(webpack.version[0]) >= 4) {
  minify = compiler.options.optimization && compiler.options.optimization.minimize
} else {
   minify = (compiler.options.plugins || []).some(plugin => {
      return plugin instanceof webpack.optimize.UglifyJsPlugin
    })
}
```

**Comment by woutervanvliet** [comment]
Thanks.

We have a workable fix for this on the next branch, but I think I like your fix better.

**Comment by masterwendu** [comment]
When are you going to deploy this fix for webpack v4?

**Comment by andresmatasuarez** [comment]
+1, is there a release date on schedule yet?

**Comment by sibelius** [comment]
is webpack 4 support ready?

**Comment by woutervanvliet** [comment]
Our fixes for webpack 4 breaks support with older versions of webpack entirely. Instead of using your suggestion, we're throwing an error on versions not supporting hooks (webpack < 4).
