### ISSUE TITLE
Unexpected using UglifyJSPlugin in development mode

### ISSUE THREAD

**Issue by budarin** [oliviertassinari/serviceworker-webpack-plugin#76]
Webpack 4
I try to use plugin in development mode and got the error:
```
			throw new RemovedPluginError(errorMessage);
			^

Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
    at Object.get [as UglifyJsPlugin] (D:\Projects\kometa_old\node_modules\webpack\lib\webpack.js:166:10)
```
ok, let it doesn't work in prod mode due to using deprecated UglifyJs, but why it uses UglifyJs in dev mode?

**Comment by devCrossNet** [comment]
Hey @budarin,
did you have a look at #72 and #65? Maybe this can solve your problems

**Comment by budarin** [comment]
Thanks for pointin, but it is hard to look through issues for solved solution - could you add this to README

**Comment by devCrossNet** [comment]
@woutervanvliet I think we could merge it into master now and release a new version on npm. what do you think?
