### ISSUE TITLE
sw.js in TypeScript?

### ISSUE THREAD

**Issue by mohsen1** [oliviertassinari/serviceworker-webpack-plugin#8]
Would it be possible to write the `sw.js` file in TypeScript. I need to import some parts of my app which is in TS.

**Comment by oliviertassinari** [comment]
I believe that we use the same loaders as the others entry points. Are you experiencing an issue. That should be working.

**Comment by mohsen1** [comment]
I didn't really try! Let me try it and update you

**Comment by mohsen1** [comment]
Yes, it simply works with TypeScript! :)

**Comment by oliviertassinari** [comment]
Great, thanks for letting me know :).
