### ISSUE TITLE
Specify absolute path

### ISSUE THREAD

**Issue by ZikDead** [oliviertassinari/serviceworker-webpack-plugin#87]
Hi. Is there any way to specify path to service worker ? Im using django webpack loader for my project and it`s located on localhost:8000, when my dev js server on localhost:3000, I need to specify another url for my service worker. Sorry for bad reply

**Comment by devCrossNet** [comment]
Hey @ZikDead ,
the service worker has to be from the same origin. Port 8000 is already another domain. You can follow this thread for more information: https://github.com/w3c/ServiceWorker/issues/940

**Comment by ZikDead** [comment]
@devCrossNet  thank you for reply. I will think how to make it work with django webpack loader
