### ISSUE TITLE
Getting a warning for setting publicPath and filename

### ISSUE THREAD

**Issue by mohsen1** [oliviertassinari/serviceworker-webpack-plugin#9]
Here is my config:

```js
        new ServiceWorkerWebpackPlugin({
            entry: join(__dirname, 'src/service-worker.ts'),
            filename: 'service-worker.js',
            publicPath: '/dist/',
        }),
```

```
ServiceWorkerPlugin: publicPath is used in conjunction with relativePaths,
          publicPath was set by the ServiceWorkerPlugin to empty string
```

How can I make the config go away?

**Comment by oliviertassinari** [comment]
You need to set `relativePaths: false`.
I'm wondering if we have a consistency issue with the options API.
Or we could improve the warning message.
What do you think?

**Comment by mohsen1** [comment]
Adding `relativePaths: false` worked. Thanks!

Maybe instead of warning look at `publicPath` and if it is absolute make `relativePaths` `false`

**Comment by oliviertassinari** [comment]
> Maybe instead of warning look at publicPath and if it is absolute make relativePaths false

Sounds good, let's make `publicPath` taking precedance over `relativePaths` and adpating the warning for when `relativePaths` isn't the default and `publicPath` is set.

**Comment by oliviertassinari** [comment]
I feel like I'm gonna soon need a test suite 🙈 .
